package mw.fstraverse.tool;

//
//This file was (initially) generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2015.03.05 at 07:50:33 PM MSK 
//



import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
* <p>Java class for anonymous complex type.
* 
* <p>The following schema fragment specifies the expected content contained within this class.
* 
* <pre>
* &lt;complexType>
*   &lt;complexContent>
*     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*       &lt;sequence>
*         &lt;element name="step" maxOccurs="unbounded" minOccurs="0">
*           &lt;complexType>
*             &lt;complexContent>
*               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*                 &lt;sequence>
*                   &lt;element name="stepID" type="{http://www.w3.org/2001/XMLSchema}string"/>
*                   &lt;element name="directory" type="{http://www.w3.org/2001/XMLSchema}string"/>
*                   &lt;element name="reportabout" type="{http://www.w3.org/2001/XMLSchema}string"/>
*                   &lt;element name="plugin" type="{http://www.w3.org/2001/XMLSchema}string"/>
*                   &lt;element name="action" type="{http://www.w3.org/2001/XMLSchema}string"/>
*                   &lt;element name="output" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
*                   &lt;element name="nextto" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
*                 &lt;/sequence>
*               &lt;/restriction>
*             &lt;/complexContent>
*           &lt;/complexType>
*         &lt;/element>
*       &lt;/sequence>
*     &lt;/restriction>
*   &lt;/complexContent>
* &lt;/complexType>
* </pre>
* 
* 
*/
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
 "step"
})
@XmlRootElement(name = "scenario")
public class ScenarioConfig {

 protected List<ScenarioConfig.Step> step;

 /**
  * Gets the value of the step property.
  * 
  * <p>
  * This accessor method returns a reference to the live list,
  * not a snapshot. Therefore any modification you make to the
  * returned list will be present inside the JAXB object.
  * This is why there is not a <CODE>set</CODE> method for the step property.
  * 
  * <p>
  * For example, to add a new item, do as follows:
  * <pre>
  *    getStep().add(newItem);
  * </pre>
  * 
  * 
  * <p>
  * Objects of the following type(s) are allowed in the list
  * {@link ScenarioConfig.Step }
  * 
  * 
  */
 public List<ScenarioConfig.Step> getStep() {
     if (step == null) {
         step = new ArrayList<ScenarioConfig.Step>();
     }
     return this.step;
 }


 /**
  * <p>Java class for anonymous complex type.
  * 
  * <p>The following schema fragment specifies the expected content contained within this class.
  * 
  * <pre>
  * &lt;complexType>
  *   &lt;complexContent>
  *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
  *       &lt;sequence>
  *         &lt;element name="stepID" type="{http://www.w3.org/2001/XMLSchema}string"/>
  *         &lt;element name="directory" type="{http://www.w3.org/2001/XMLSchema}string"/>
  *         &lt;element name="reportabout" type="{http://www.w3.org/2001/XMLSchema}string"/>
  *         &lt;element name="plugin" type="{http://www.w3.org/2001/XMLSchema}string"/>
  *         &lt;element name="action" type="{http://www.w3.org/2001/XMLSchema}string"/>
  *         &lt;element name="output" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
  *         &lt;element name="nextto" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
  *       &lt;/sequence>
  *     &lt;/restriction>
  *   &lt;/complexContent>
  * &lt;/complexType>
  * </pre>
  * 
  * 
  */
 @XmlAccessorType(XmlAccessType.FIELD)
 @XmlType(name = "", propOrder = {
     "stepID",
     "directory",
     "reportabout",
     "plugin",
     "action",
     "output",
     "nextto"
 })
 public static class Step {

     @Override
    public String toString() {
        return "Step [stepID=" + stepID + ", directory=" + directory
                + ", reportabout=" + reportabout
                + ", plugin=" + plugin + ", action=" + action + ", output="
                + output + ", nextto=" + nextto + "]";
    }

    public Step() {
    }

    @XmlElement(required = true)
     protected String stepID;
     @XmlElement(required = true)
     protected String directory;
     protected String reportabout;
     @XmlElement(required = true)
     protected String plugin;
     @XmlElement(required = true)
     protected String action;
     protected String output;
     protected String nextto;

     /**
      * Gets the value of the stepID property.
      * 
      * @return
      *     possible object is
      *     {@link String }
      *     
      */
     public String getStepID() {
         return stepID;
     }

     /**
      * Sets the value of the stepID property.
      * 
      * @param value
      *     allowed object is
      *     {@link String }
      *     
      */
     public void setStepID(String value) {
         this.stepID = value;
     }

     /**
      * Gets the value of the directory property.
      * 
      * @return
      *     possible object is
      *     {@link String }
      *     
      */
     public String getDirectory() {
         return directory;
     }

     /**
      * Sets the value of the directory property.
      * 
      * @param value
      *     allowed object is
      *     {@link String }
      *     
      */
     public void setDirectory(String value) {
         this.directory = value;
     }

     /**
      * Gets the value of the reportabout property.
      * 
      * @return
      *     possible object is
      *     {@link String }
      *     
      */
     public String getReportabout() {
         return reportabout;
     }

     /**
      * Sets the value of the reportabout property.
      * 
      * @param value
      *     allowed object is
      *     {@link String }
      *     
      */
     public void setReportabout(String value) {
         this.reportabout = value;
     }

     /**
      * Gets the value of the plugin property.
      * 
      * @return
      *     possible object is
      *     {@link String }
      *     
      */
     public String getPlugin() {
         return plugin;
     }

     /**
      * Sets the value of the plugin property.
      * 
      * @param value
      *     allowed object is
      *     {@link String }
      *     
      */
     public void setPlugin(String value) {
         this.plugin = value;
     }

     /**
      * Gets the value of the action property.
      * 
      * @return
      *     possible object is
      *     {@link String }
      *     
      */
     public String getAction() {
         return action;
     }

     /**
      * Sets the value of the action property.
      * 
      * @param value
      *     allowed object is
      *     {@link String }
      *     
      */
     public void setAction(String value) {
         this.action = value;
     }

     /**
      * Gets the value of the output property.
      * 
      * @return
      *     possible object is
      *     {@link String }
      *     
      */
     public String getOutput() {
         return output;
     }

     /**
      * Sets the value of the output property.
      * 
      * @param value
      *     allowed object is
      *     {@link String }
      *     
      */
     public void setOutput(String value) {
         this.output = value;
     }

     /**
      * Gets the value of the nextto property.
      * 
      * @return
      *     possible object is
      *     {@link String }
      *     
      */
     public String getNextto() {
         return nextto;
     }

     /**
      * Sets the value of the nextto property.
      * 
      * @param value
      *     allowed object is
      *     {@link String }
      *     
      */
     public void setNextto(String value) {
         this.nextto = value;
     }

 }

}
